<?php
/** @var $this Menu */

use App\App;
use App\libs\App\Helper;
use App\libs\App\Router;
use BaseProject\Admin\Block\Menu;
use BaseProject\Login\Helper\Login;

$menu = $this->getMenu();
$labelsMenu = $this->getLabelsMenu();
?>

<nav class="navbar navbar-custom admin">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"
               href="<?= Router::getUrlAction('Admin', 'Index', 'index') ?>"><?= $this->__('Administration'); ?></a>
        </div>
    </div>
</nav>
<div class="col-sm-3 col-lg-2 sidebar collapse in">
    <div class="profile">
        <img src="https://d30y9cdsu7xlg0.cloudfront.net/png/16627-200.png" />
        <div class="user-title">
            PIFFETEAU Matthieu<br/>
            <a href="#">Disconnect</a>
        </div>
    </div>
    <ul class="menu">
        <li><a>Test</a></li>
        <li><a>Test</a></li>
        <li>Test
            <ul>
                <li><a>Test 1</a></li>
            </ul>
        </li>
    </ul>
</div>

<script type="application/javascript">
    jQuery(function ($) {
        $('ul.dropdown-menu [data-toggle=dropdown]').on('click', function (event) {
            // Avoid following the href location when clicking
            event.preventDefault();
            // Avoid having the menu to close when clicking
            event.stopPropagation();
            // If a menu is already open we close it
            $('ul.dropdown-menu [data-toggle=dropdown]').parent().removeClass('open');
            // opening the one you clicked on
            $(this).parent().addClass('open');
        });
    });
</script>