<?php
/** @var $this Menu */

use App\App;
use App\libs\App\Helper;
use App\libs\App\Router;
use BaseProject\Admin\Block\Menu;
use BaseProject\Login\Helper\Login;

$menu = $this->getMenu();
$labelsMenu = $this->getLabelsMenu();
?>

<nav class="navbar navbar-inverse admin">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand"
               href="<?= Router::getUrlAction('Admin', 'Index', 'index') ?>"><?= $this->__('Administration'); ?></a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <?php foreach ($menu as $code => $child): ?>
                    <?php
                    $hasChild = is_array($child);
                    ?>
                    <li <?= ($hasChild) ? 'class="dropdown"' : '' ?>>
                        <a <? if (!$hasChild): ?>href="<?= $this->getUrl($code) ?>" <? endif; ?> <?= ($hasChild) ? 'class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"' : '' ?>><?= $this->__(($hasChild) ? $labelsMenu[$code] : $labelsMenu[$child]) ?><? if ($hasChild): ?>
                                <span class="caret"></span><? endif; ?></a>
                        <?php
                        if ($hasChild) :?>
                            <ul class="dropdown-menu level2">
                                <?php
                                foreach ($child as $code2 => $child2): ?>
                                    <?php
                                    $hasChild2 = is_array($child2);
                                    ?>
                                    <li <?= ($hasChild2) ? 'class="dropdown"' : '' ?>>
                                        <a <? if (!$hasChild2): ?>href="<?= $this->getUrl($child2) ?>" <? endif; ?> <?= ($hasChild2) ? 'class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"' : '' ?>><?= $this->__(($hasChild2) ? $labelsMenu[$code2] : $labelsMenu[$child2]) ?><? if ($hasChild2): ?>
                                                <span class="caret"></span><? endif; ?></a>
                                        <?php
                                        if ($hasChild2): ?>
                                            <ul class="dropdown-menu level3">
                                                <?php
                                                foreach ($child2 as $code3 => $child3):
                                                    ?>
                                                    <li>
                                                        <a href="<?= $this->getUrl($child3) ?>"><?= $this->__($labelsMenu[$child3]) ?></a>
                                                    </li>
                                                    <?php
                                                endforeach;
                                                ?>
                                            </ul>
                                            <?php
                                        endif;
                                        ?>
                                    </li>
                                    <?php
                                endforeach;
                                ?>
                            </ul>
                        <?php endif; ?>
                    </li>
                <?php endforeach; ?>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <span class="fa fa-user fa-1-5x"></span><span class="caret"></span>
                    </a>
                    <?php
                    if ($user = App::getInstance()->getSession()->getUser()):
                        ?>
                        <ul class="dropdown-menu">
                            <li style="padding-left: 20px; color: grey;"><?= $this->__('Welcome') ?>
                                &nbsp;<?= $user->getUsername() ?></li>
                            <li><a href="<?= Router::getUrlAction('Login', 'Index',
                                    'disconnect') ?>"><?= $this->__('Disconnect') ?></a></li>
                        </ul>
                        <?php
                    else:
                        /** @var Login $helper */
                        $helper = Helper::getInstance('Login_Login');
                        ?>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?= $helper->getUrlLogin() ?>"><?= $this->__('Connect') ?></a>
                            </li>
                        </ul>
                    <?php endif; ?>
                </li>
            </ul>
        </div>
    </div>
</nav>

<script type="application/javascript">
    jQuery(function ($) {
        $('ul.dropdown-menu [data-toggle=dropdown]').on('click', function (event) {
            // Avoid following the href location when clicking
            event.preventDefault();
            // Avoid having the menu to close when clicking
            event.stopPropagation();
            // If a menu is already open we close it
            $('ul.dropdown-menu [data-toggle=dropdown]').parent().removeClass('open');
            // opening the one you clicked on
            $(this).parent().addClass('open');
        });
    });
</script>