<?php
/** @var \BaseProject\Admin\Block\Message $this */
$messages = $this->getMessages();

/** @var \App\libs\App\Message $message */
foreach ($messages as $message):?>
    <div class="message">
        <div class="message-content <?= $this->getClass($message->getLevel()) ?>" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span>
            </button>
            <?= $message->getMessage() ?>
        </div>
    </div>
<?php
endforeach;