<?php
/** @var \BaseProject\Cms\Block\Media\ListBlock $this */
$elements = $this->getElementsDir('/');
?>
<div class="list">
    <?= $this->getUl($elements); ?>
</div>
<script type="application/javascript">
    jQuery(function ($) {
        $('li.dir>span').on('click', function () {
            var li = $(this).parent('li');
            var span = $(this);
            if (li.hasClass('close-dir')) {
                li.removeClass('close-dir');
                span.addClass('fa-folder-open');
                span.removeClass('fa-folder');
            } else {
                li.addClass('close-dir');
                span.addClass('fa-folder');
                span.removeClass('fa-folder-open');
            }
        });

        $('li.dir').on('click', function() {
            var li = $(this);
            var path = li.data('path');
            $('input[name="path"]').val(path);
        });
    });
</script>
