<?php
/** @var \BaseProject\Cms\Block\PopIn $this */
?>
<div class="modal fade" tabindex="-1" role="dialog" id="<?= $this->getId() ?>">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="gridSystemModalLabel"><?= $this->getTitle() ?></h4>
            </div>
            <div class="modal-body">
                <?= $this->getBody() ?>
            </div>
            <div class="modal-footer">
                <?php
                foreach ($this->getButtons() as $button):
                    echo $button;
                endforeach;
                ?>
            </div>
        </div>
    </div>
</div>