<?php
/** @var \BaseProject\Task\Controller\Scheduler $this */
$schedulers = $this->getSchedulers();
?>

<div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-12">
        <a href="<?= \App\libs\App\Router::getUrlAction('Task', 'Scheduler', 'scheduler') ?>"
           class="btn btn-default"><?= $this->__('New scheduler') ?></a>
        <table class="table table-hover">
            <thead>
            <tr>
                <th><?= $this->__('Id'); ?></th>
                <th><?= $this->__('Task code'); ?></th>
                <th><?= $this->__('Last execution'); ?></th>
                <th><?= $this->__('Next execution'); ?></th>
            </tr>
            </thead>
            <tbody>
            <?php
            /** @var \BaseProject\Task\Model\Scheduler $scheduler */
            foreach ($schedulers as $scheduler):
                ?>
                <tr>
                    <td><?= $scheduler->getId() ?></td>
                    <td><a href="<?= \App\libs\App\Router::getUrlAction('Task', 'Scheduler', 'scheduler').'/id/'.$scheduler->getId() ?>"><?= $scheduler->getTaskCode() ?></a></td>
                    <td><?= $scheduler->getLastExecution() ?></td>
                    <td><?= $scheduler->getNextRunDate()->format('Y/m/d H:i:s') ?></td>
                </tr>
                <?php
            endforeach;
            ?>
            </tbody>
        </table>
    </div>
</div>
